"""add updated_at to games

Revision ID: 4301a7eb3cf0
Revises: d3eb6750106c
Create Date: 2025-12-06 17:02:05.652508+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4301a7eb3cf0'
down_revision: Union[str, Sequence[str], None] = 'd3eb6750106c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'updated_at')
    # ### end Alembic commands ###
